version: '3.7'

services:
    app:
        image: app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION:-8.1}
        volumes:
            - ./:/var/www/app
            - /var/www/app/vendor
        extra_hosts:
            - "internal.host:host-gateway"
        networks:
            - app-net
    nginx:
        image: nginx:alpine
        ports:
            - "${APP_PORT:-8283}:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./:/var/www/app:cached
        restart: on-failure
        depends_on:
            - app
        networks:
            - app-net
    supervisor:
        image: app
        networks:
            - app-net
        depends_on:
            - app
            - nginx
        command: supervisord

    postgres_api:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: agenda_inteligente
        networks:
            - app-net
        depends_on:
            - app
            - nginx
            - supervisor

networks:
    app-net:
        driver: bridge

volumes:
    pgdata:
        driver: "local"
