version: '3'

services:
  laravel-api:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - agenda-network

  postgres-api:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - docker-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: agenda_inteligente
    networks:
      - agenda-network

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres-api
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge

volumes:
  docker-dbdata:
    driver: "local"
